### ISSUE TITLE
More New Achievements Have Been Updated

### ISSUE THREAD

**Issue by Schweinepriester** [Schweinepriester/github-profile-achievements#112]
### Discussed in https://github.com/Schweinepriester/github-profile-achievements/discussions/111

<div type='discussions-op-text'>

<sup>Originally posted by **lnugraha** July 13, 2022</sup>
Today (July 13, 2021) I noticed that Github has just updated their achievement badges. I have identified the following new badges and how to earn them (please CMIIW)

1. Quickdraw: close an open issue (or pull request?) within 5 minutes; apparently one-shot like YOLO thing.

2. Pair Extraordinaire: coauthorized commits on merged pull request

3. Starstruck: earn at least 16 stars (from a single repository?) that you own</div>

**Comment by Schweinepriester** [comment]
High examples:
- https://github.com/Schweinepriester?achievement=quickdraw&tab=achievements
- https://github.com/ljharb?achievement=pair-extraordinaire&tab=achievements
- https://github.com/torvalds?achievement=starstruck&tab=achievements

Pair extraordinaire x4 is missing

**Comment by Rongronggg9** [comment]
> Pair extraordinaire x4 is missing

https://github.com/Rongronggg9?tab=achievements&achievement=pair-extraordinaire
