### ISSUE TITLE
Grammar typo in README.md

### ISSUE THREAD

**Issue by d3li0n** [Schweinepriester/github-profile-achievements#14]
Hello, thanks for the information about the new achievement, it's very helpful to know how to get the achievements in the new update. 

I noticed a small typo in your README.md file in sentence below:

`Don't like the Achievements? [Here](https://docs.github.com/account-and-profile/setting-up-and-managing-your-github-profile/managing-contribution-settings-on-your-profile/showing-your-private-contributions-and-achievements-on-your-profile#changing-the-visibility-of-achievements) is is how to disable them. [Direct link to the setting for your convenience](https://github.com/settings/profile#profile-settings-heading).`

The typo is in this line

`is is how to disable them`

**Comment by Schweinepriester** [comment]
Fixed, thank you!
