### ISSUE TITLE
Emoji skin tones not listed

### ISSUE THREAD

**Issue by seanpm2001** [Schweinepriester/github-profile-achievements#203]
I have noticed that the color of the Starstruck and Gitty up achievements look different depending on the users preference on Emoji skin tone. I assume any achievement with a facial emoji will have this.
Here is an example I just recently saw:
<img width="148" alt="quickdraw-default--light-medium" src="https://user-images.githubusercontent.com/65933340/179626491-771af009-9456-4f24-a89d-df3857cb0f31.png">

**Comment by seanpm2001** [comment]
Nevermind, I just went back. They are already included. This issue is now closed. Sorry for wasting your time.

**Comment by Schweinepriester** [comment]
B-)
