### ISSUE TITLE
xNumber displayed in the badge

### ISSUE THREAD

**Issue by thomscoder** [Schweinepriester/github-profile-achievements#22]
I'm coming from the Github-Community discussions where it seems people are somehow misunderstatning the <b>xNumber</b> displayed in the badge.

My proposal is to add in the README.md a column starting from the base tier that explains 
x1 - Base tier
x2 - Bronze tier
x3 - Silver tier
x4 - Gold tier

💯

**Comment by thomscoder** [comment]
> Do you have a link to such a discussion?
> 
> Mh, not sure about "x1" because the base tier doesn't have that: ![image](https://user-images.githubusercontent.com/2644614/174036596-8c08e847-654c-4dca-8bf0-56f82b5c7528.png)

Hi,
I've seen: 
- https://github.com/github-community/community/discussions/18298
- https://github.com/github-community/community/discussions/18703

x1 might be unnecessary yup, thanks for the feedback

**Comment by Schweinepriester** [comment]
I've merged https://github.com/Schweinepriester/github-profile-achievements/pull/23 to give you the props, but I will rearrange a bit. Thank you!
