### ISSUE TITLE
new release for the new achivements

### ISSUE THREAD

**Issue by devkennyy** [Schweinepriester/github-profile-achievements#238]
its been a while since the new achivements were released. any plans on releasing a new release?

**Comment by Schweinepriester** [comment]
absolutely! though it probably will be a bit.

gonna leave this issue open as reminder.

out of interest, why would you like to have a new release?

**Comment by devkennyy** [comment]
just to keep the repo updated and fresh really. keep users updated.

**Comment by vinsdragonis** [comment]
Hey! Just as `Starstruck` is given to a user maintaining a repo with 16 stars, wouldn't it be cooler if we had a similar badge for the number of forks? You know, a repository with 10, 20, 40 forks, and so on as an example.

**Comment by orSolocate** [comment]
@vinsdragonis  sounds like a nice idea.  And if you follow the same way of thinking maybe you could add a `number of followers` badge.

**Comment by Schweinepriester** [comment]
finally have done the release in light of [probable additions shortly](https://github.com/Schweinepriester/github-profile-achievements/discussions/469) 
→ https://github.com/Schweinepriester/github-profile-achievements/releases/tag/v3.0.0
