### ISSUE TITLE
Add link to Rejected GitHub Profile Achievements

### ISSUE THREAD

**Issue by Schweinepriester** [Schweinepriester/github-profile-achievements#239]
- https://twitter.com/schweinepriestr/status/1548693296666533889
- https://github.com/Flet/rejected-github-profile-achievements

**Comment by cesarreyes3** [comment]
@Schweinepriester How about unicorn achievements 
![image](https://user-images.githubusercontent.com/109559100/181369670-7ee6d6a2-231f-4cbd-a4ab-844e3a4fb348.png)
Make your profile imposible to watch
Example: https://github.com/paledega

**Comment by Schweinepriester** [comment]
@Flet see above ^ :D

Saving the image here:
![image](https://user-images.githubusercontent.com/2644614/181385133-df3a04ac-af3f-4c11-bd61-5e1ec80c601b.png)

**Comment by Schweinepriester** [comment]
finally added via https://github.com/Schweinepriester/github-profile-achievements/commit/d829a54d6cf69dfd8c0b572a9d3290e24faa764a
