### ISSUE TITLE
> Por supuesto. Esperando los SVG terminados. Los de "prueba" actuales ya me resultan impresionantes :)

### ISSUE THREAD

**Issue by Arantxa12** [Schweinepriester/github-profile-achievements#33]
> Por supuesto. Esperando los SVG terminados. Los de "prueba" actuales ya me resultan impresionantes :)

_Originally posted by @Arantxa12 in https://github.com/Schweinepriester/github-profile-achievements/issues/31#issuecomment-1159948519_

**Comment by Schweinepriester** [comment]
Spam?
