### ISSUE TITLE
Found GitHub user with all achievements

### ISSUE THREAD

**Issue by xafn** [Schweinepriester/github-profile-achievements#510]
https://github.com/twpayne
Though, they have Tier 2 for `Pair Extraordinaire` and Tier 3 for `Galaxy Brain` .

**Comment by Schweinepriester** [comment]
Thank you, another one to look out for! :)

Via https://github.com/Schweinepriester/github-profile-achievements/discussions/211 the closest so far we know are https://github.com/messense?tab=achievements and https://github.com/max-sixty?tab=achievements, each only one achievement not max tier.
