### ISSUE TITLE
Disable Discussions

### ISSUE THREAD

**Issue by akirataguchi115** [Schweinepriester/github-profile-achievements#515]
This might be a wild suggestion but I'm going to put this here anyway: We should disable Discussions and focus on Issues when moving forward.

This repository's Discussions are currently filled with Starstruck, Galaxy Brain and many other cheap hacks. In the spirit of FOSS and [GitHub's own words](https://github.blog/2022-06-09-introducing-achievements-recognizing-the-many-stages-of-a-developers-coding-journey/) the Achievements should be for "-recognizing the many stages of a developer’s coding journey". These cheap hacks don't support this ideal. Earning these achievements in actual helpful and contributing scenarios would be just for the FOSS community.
Plus the cheap achievements look super wack when actually clicked on one's profile. Looking at [your ](https://github.com/Schweinepriester/github-profile-achievements/discussions/345#discussioncomment-3471752)way @Schweinepriester 😉 

Thoughts?

**Comment by Schweinepriester** [comment]
Had thought about limiting it in some way as well, but then again if it's not prevented by GitHub themselves, people just going to go elsewhere…

Leaving open for _discussions_ ;)

**Comment by akirataguchi115** [comment]
Haha yeah I thought about that as well when I wrote this issue. But then I figured distributing these kind of users to different repositories

1. Encourages them to actually somehow contribute somehow to the Discussions they are writing into.
2. Helps the reporting process due to the distributed state of these misusers.

But yeah leaving this issue open for _discussions_ as well:octocat:

**Comment by Schweinepriester** [comment]
I have made up my mind and posted this: https://github.com/Schweinepriester/github-profile-achievements/discussions/722

I'll leave everything as is for now, see if that is read organically (doubt it) and eventually will start locking existing discussion and escalate from there, if need be.

**Comment by akirataguchi115** [comment]
Excellent choice of actions. Thanks for fixing the situation ❤️
