### ISSUE TITLE
Pair Extraordinaire achievement not working

### ISSUE THREAD

**Issue by CodeMaster7000** [Schweinepriester/github-profile-achievements#547]
I have fulfilled the requirements for the achievement in the title of this issue, and have waited 16 hours since completing it, but it is still failing to show on my profile.

**Comment by SmashedFrenzy16** [comment]
@CodeMaster7000, I think the best place to go for this issue is the GitHub community in the discussions area. The achievements here are to inform about the achievements made by GitHub themselves.

**Comment by CodeMaster7000** [comment]
@SmashedFrenzy16 Thanks, but there is a chance someone responds and attempts to fix the issue here.

**Comment by PSGitHubUser1** [comment]
How you didn't got it. I got it see my profile..? it's confusing.

**Comment by CodeMaster7000** [comment]
@PSGitHubUser1 Despite adding someone as a co-author to a merged PR, I still have not obtained the achievement.

**Comment by PSGitHubUser1** [comment]
Oh

**Comment by CodeMaster7000** [comment]
![image](https://user-images.githubusercontent.com/95772109/219427954-003dc4a7-10fc-40d6-a158-07547c989888.png)

**Comment by CodeMaster7000** [comment]
In my experience, these achievements can be quite glitchy or take a long time to show up. I closed the issue I had just made and edited this one since I was having trouble with the YOLO one.
