### ISSUE TITLE
Suggestion for `Open Sourcerer`

### ISSUE THREAD

**Issue by PSGitHubUser1** [Schweinepriester/github-profile-achievements#566]
Suggestion for 'Open Sourcerer': Can be obtained by making 15 repos and 2 open source repos.

**Comment by Schweinepriester** [comment]
I'm afraid suggesting it here has no power - or do you mean you know someone who has got it that way?

**Comment by HyunseungLee-Travis** [comment]
@PSGitHubUser1 This repository is for badges you get in GutHub.

The open sourcerer, as far as the public knows, nobody got it.

GitHub is not planning on giving g out the details before somebody gets the badge.

I think what you are confused about is that this repository is something about badges people can customize, but this is absolutely up to GitHub to do this.
