### ISSUE TITLE
Pair Extraordinaire achievement not appearing on web version of GitHub

### ISSUE THREAD

**Issue by CodeMaster7000** [Schweinepriester/github-profile-achievements#657]
![Screenshot 2023-02-23 203801](https://user-images.githubusercontent.com/95772109/221024605-ab07312c-9342-4205-96ed-9ac9103e553f.png)

On the GitHub mobile app, it says that I have unlocked Pair Extraordinaire, however, this is not reflected in the web version of GitHub. Is there any way this problem can be resolved?

**Comment by Schweinepriester** [comment]
do you also have a screenshot of the mobile app showing it?

**Comment by CodeMaster7000** [comment]
![20230224_065209.jpg](https://user-images.githubusercontent.com/95772109/221112234-7bc84b0f-4a18-4cd4-ba94-5f3901729e43.jpg)

@Schweinepriester Here is the screenshot (I have since unlocked Galaxy Brain too).

**Comment by CodeMaster7000** [comment]
Thanks!
