### ISSUE TITLE
My achievements are not appearing in my GitHub profile

### ISSUE THREAD

**Issue by CesarCanoff** [Schweinepriester/github-profile-achievements#691]
My achievements are not appearing in my GitHub profile, weeks ago they were there, but since a few days ago, they disappeared out of nowhere.

Weeks ago I created a discussion about this: [Discussion](https://github.com/orgs/community/discussions/50552), and @CodeMaster7000 recommended me to open an issue here.

![image](https://user-images.githubusercontent.com/82189342/228026169-913c8644-ba69-4f72-b568-1832eefeb3ad.png)

**Comment by cesarcanoff** [comment]
Hi @SmashedFrenzy16 and @CodeMaster7000

I am aware that it may take a few days, and that there may be no solution because it is a GitHub problem, if there is no solution here, I will contact GitHub Support.

Best for you!

**Comment by Schweinepriester** [comment]
@CesarCanoff 

Thanks for creating the issue and therefore making me aware of this bug!

However as I'm not affiliated with GitHub, I'm afraid you have to contact GitHub Support to hopefully fix this… 🤞 

Please report back if/when they fix it and if they say anything more about the reason :)

**Comment by cesarcanoff** [comment]
Greetings,

The problem of all achievements disappearing has been solved here:
https://support.github.com/ticket/personal/0/2111013

I appreciate everyone's time and effort to help.

With kind regards,
Cesar
