### ISSUE TITLE
Remove achievements that cannot be obtained from achievements list

### ISSUE THREAD

**Issue by CodeMaster7000** [Schweinepriester/github-profile-achievements#698]
Keep only achievements that are currently obtainable in the achievements list, and open up new sections for "past" achievements e.g. Mars Helicopter 2020, and "upcoming" achievements for those in the planning phase.

**Comment by SmashedFrenzy16** [comment]
@CodeMaster7000, resolved here: #696

**Comment by Schweinepriester** [comment]
Will indeed be resolved by https://github.com/Schweinepriester/github-profile-achievements/issues/696, though I like OPs wording, will copy it over!
