### ISSUE TITLE
Can't earn 'Heart on Your Sleeve' achievement by reacting to something on GitHub with a ❤️ emoji. 

### ISSUE THREAD

**Issue by Mehul2203** [Schweinepriester/github-profile-achievements#754]
I reacted to some of the comments in a few discussions with a ❤️ emoji, but don't see the achievement on my profile. If we can earn this achievement by reacting with a ❤️ emoji then maybe there's a limit that you should react 20 times, 50 times, or something. On GitHub, I think we can only react to the discussions, is there anywhere else we can react in any other way? 
For now, I'm assuming that we can earn this by getting ❤️ emoji reactions from others on our comments in various discussions. 
Please share your kind reviews on this issue guys. 
Thank you! 😊

**Comment by Yashbadjatya** [comment]
ya i think it is under process
