### ISSUE TITLE
Can you give me a Galaxy Brain badge?

### ISSUE THREAD

**Issue by p2kalita** [Schweinepriester/github-profile-achievements#774]
Can you give me a Galaxy Brain badge?

_Originally posted by @fynntang in https://github.com/Schweinepriester/github-profile-achievements/discussions/9#discussioncomment-2970232_

**Comment by p2kalita** [comment]
test

**Comment by Schweinepriester** [comment]
@p2kalita stop spamming or I‘ll have to block you.

**Comment by p2kalita** [comment]
Sorrie
