### ISSUE TITLE
Will the `heart on the sleeve` badge appear on profiles soon?

### ISSUE THREAD

**Issue by CodeMaster7000** [Schweinepriester/github-profile-achievements#801]
Will the heart on the sleeve badge appear on profiles soon? I have not seen users having it yet.

**Comment by Schweinepriester** [comment]
Unknown, up to GitHub (I'm not associated with them).

Most recent information is still here: https://github.com/Schweinepriester/github-profile-achievements/issues/478#issuecomment-1522938751

Feel free to follow that issue.
