### ISSUE TITLE
Your Thoughts on Badges? 🛡️

### ISSUE THREAD

**Issue by Aparnaraha** [Schweinepriester/github-profile-achievements#863]
Hey everyone,

I'm keen on sprucing up our project's GitHub with badges. What badges do you find useful or interesting? Any ideas on how we can earn them? Drop your thoughts below!

Cheers,
AparnaRaha

**Comment by Schweinepriester** [comment]
Let's stick to [that discussion](https://github.com/Schweinepriester/github-profile-achievements/discussions/862) ;)
