### ISSUE TITLE
Achievements are missing from my profile

### ISSUE THREAD

**Issue by conorheffron** [Schweinepriester/github-profile-achievements#878]
**Select Topic Area**
Bug

**Body**
Hello, I would like to ask what I need to do to get my achievements back on my profile, my profile appears to be missing a few.
See further screenshots of profile config and warning message below.

If someone knows how to solve it, I would be grateful!
Thank you in advance!
Conor

![Capture](https://github.com/Schweinepriester/github-profile-achievements/assets/8218626/1b3d2eb8-db0f-45dc-92ff-d1dae7775e10)
![Capture2](https://github.com/Schweinepriester/github-profile-achievements/assets/8218626/9796db45-de08-4dfd-9d35-1e3c42561a3b)

**Comment by conorheffron** [comment]
only 1x pull shark achievement displayed after updating config which is from 2017

**Comment by Schweinepriester** [comment]
I guess best would be to contact GitHub support:  
https://docs.github.com/en/support/contacting-github-support/creating-a-support-ticket  
=> https://support.github.com/request

I'll leave this issue open for the time being in case anybody knows, but please let us know if support can help you :)

**Comment by conorheffron** [comment]
I opened a ticket with Github support and they re-ran a job which pulled in the missing achievement - make sure profile settings are correct / enabled.

Thanks for help.
