### ISSUE TITLE
Prototype-Function

### ISSUE THREAD

**Issue by ATHAANGGORO10** [Schweinepriester/github-profile-achievements#880]

**Comment by ATHAANGGORO10** [comment]
yeeepeyyy

**Comment by AttaAnggoro** [comment]
Huhuh

**Comment by Schweinepriester** [comment]
@ATHAANGGORO10 please stop spamming and experiment in your own repo or I‘ll have to block you.

**Comment by ATHAANGGORO10** [comment]
saya sedang mencoba beberapa fitur yang saya baru tahu. aku minta maaf

**Comment by ATHAANGGORO10** [comment]
I'm trying out some features I just found out about. I apologize, sorry for my ignorance

**Comment by ATHAANGGORO10** [comment]
Do you know how to get out of the problem?, I don't want to try it again

**Comment by ATHAANGGORO10** [comment]
> @ATHAANGGORO10 You are the owner, why don't you just delete my issue. If you delete it, I won't bother you anymore. Actually, that's what I expect from you

**Comment by ATHAANGGORO10** [comment]
@Schweinepriester You are the owner, why don't you just delete my issue. If you delete it, I won't bother you anymore. Actually, that's what I expect from you
