### ISSUE TITLE
Learning Github

### ISSUE THREAD

**Issue by ATHAANGGORO10** [Schweinepriester/github-profile-achievements#881]

**Comment by ATHAANGGORO10** [comment]
Please Reopened

**Comment by AttaAnggoro** [comment]
Huhuhu

**Comment by ATHAANGGORO10** [comment]
Hi, How do I get out of this issue. I want to go out

**Comment by ATHAANGGORO10** [comment]
Please, if I leave issuu I won't bother you anymore😭

**Comment by ATHAANGGORO10** [comment]
Please, if I leave issuu I won't bother you anymore😭

**Comment by ATHAANGGORO10** [comment]
Please

**Comment by Schweinepriester** [comment]
@ATHAANGGORO10 simply stop commenting?
