### ISSUE TITLE
Galaxy Brain Achievement Test

### ISSUE THREAD

**Issue by ATHAANGGORO10** [Schweinepriester/github-profile-achievements#882]
### Discussed in https://github.com/Schweinepriester/github-profile-achievements/discussions/45

<div type='discussions-op-text'>

<sup>Originally posted by **keyiflerolsun** June 22, 2022</sup>
Should I start two discussions or answer two discussions ?:)</div>

**Comment by ATHAANGGORO10** [comment]
hai

**Comment by ATHAANGGORO10** [comment]
Please Reopened

**Comment by AttaAnggoro** [comment]
hi

**Comment by AttaAnggoro** [comment]
Huhuu

**Comment by ATHAANGGORO10** [comment]
Hi, How do I get out of this issue. I want to go out

**Comment by ATHAANGGORO10** [comment]
huhu

**Comment by ATHAANGGORO10** [comment]
Please just get me out of here I'm not bothering you anymore. I'll stop
