### ISSUE TITLE
I want that badge!

### ISSUE THREAD

**Issue by SietseDEV** [Schweinepriester/github-profile-achievements#884]
Hello!

**Comment by ATHAANGGORO10** [comment]
@SietseDEV Hi, can you just delete this issue, this issue is completely useless and just neglected.

**Comment by ATHAANGGORO10** [comment]
@SietseDEV This aims to ensure that no issues are neglected

**Comment by ATHAANGGORO10** [comment]
@SietseDEV hi?

**Comment by SietseDEV** [comment]
It's literally closed

**Comment by SietseDEV** [comment]
On the issues page you will see the open ones only except when you filter to closed ones

**Comment by ATHAANGGORO10** [comment]
ohhhhmyyygodddd It's like North Korea

**Comment by ATHAANGGORO10** [comment]
![Screenshot_2024-01-24-07-26-45-886_com android chrome](https://github.com/Schweinepriester/github-profile-achievements/assets/136944540/a7fb0173-b57a-4aa1-8999-01c1b013a4cf)
The problem is that you entered my repository and I checked my repo and you weren't there

**Comment by ATHAANGGORO10** [comment]
That's what made me want to find out what the solution was

**Comment by ATHAANGGORO10** [comment]
@Schweinepriester Delete These Issues So That I Can Be Free
