### ISSUE TITLE
New announcement about the achievements!

### ISSUE THREAD

**Issue by ArtyomVancyan** [Schweinepriester/github-profile-achievements#892]
This [announcement](https://github.com/orgs/community/discussions/106536) on the GitHub Community is something that should be taken notes from and added in the README.

**Comment by Schweinepriester** [comment]
Just saw it as well and absolutely concur, will do later!

**Comment by Schweinepriester** [comment]
added to the README in the referenced commit as well as in https://github.com/Schweinepriester/github-profile-achievements/discussions/722.
