### ISSUE TITLE
Ya Know ! For Test

### ISSUE THREAD

**Issue by ymbtc757** [Schweinepriester/github-profile-achievements#942]
### Discussed in https://github.com/Schweinepriester/github-profile-achievements/discussions/47

<div type='discussions-op-text'>

<sup>Originally posted by **quicksandzn** June 22, 2022</sup>
Ya Know ! For Test
Ya Know ! For Test
Ya Know ! For Test</div>

**Comment by ymbtc757** [comment]
i know

**Comment by Schweinepriester** [comment]
@ymbtc757 stop spamming or I'll block you.
