### ISSUE TITLE
another mistake - Heart On Your Sleeve

### ISSUE THREAD

**Issue by AlgorithmAlchemy** [Schweinepriester/github-profile-achievements#952]
As soon as I noticed the achievement wasn’t working, I got frustrated! Either update to show that it’s not functional, or provide clear instructions on how to unlock it! Liking Issues didn’t produce any results.

**Comment by Schweinepriester** [comment]
Fixed https://github.com/Schweinepriester/github-profile-achievements/commit/c52c6767883d49245ec7ccb8a2f4b97c595559d3
